app:
  port: 10010
  loadDoc: true
  query:
    pageSize: 1000
ui:
  swaggerUi: '/docs'
  apiDocs: '/api/docs'
datasource:
  pgURL: 'postgres://indytechcook@localhost:5432/petstore'
  modelsDirectory: './api/models'
  dbOptions:
    native: true
auth0:
  client: ''
  secret: ''
storage:
  aws:
    accessKeyId: XXX
    secretAccessKey: XXX
    bucket: XXX
    region: us-east-1
auth:
  enabled: false
  perms:
    - challengeApp
  paths:
    - httpVerb: DELETE
      path: '*'
    - httpVerb: PUT
      path: '*'
    - httpVerb: POST
      path: '*'